### ISSUE TITLE
Fix display on mobile.

### ISSUE THREAD

**Issue by Dorus** [waltheri/wgo.js#88]
See https://github.com/gcp/leela-zero/issues/412#issuecomment-353960893

If black passes, you need to scroll at the bottom to see the result.

Before scroll:

![2017-12-26 12 56 46](https://user-images.githubusercontent.com/4461459/34356269-b7486ab2-ea3c-11e7-9933-2a65cd5a31bb.png)

After scroll:

![2017-12-26 13 00 46](https://user-images.githubusercontent.com/4461459/34356297-e0bdff7e-ea3c-11e7-8508-2bc7caeab295.png)

There are 2 problems with the CSS:

wgo.player.css:375
```css
.wgo-player-top .wgo-comments-content, .wgo-player-bottom .wgo-comments-content {
    position: absolute;
}
```
Here "absolute" should be "relative".

wgo.player.css:394
```css
.wgo-player-top .wgo-comments-wrapper, .wgo-player-bottom .wgo-comments-wrapper {
    height: 150px;
}
```
Here should be no height indication.
